### ISSUE TITLE
mastera sertifikasi, ogretmenden ders removelama

### ISSUE THREAD

**Issue by em1rR** [mufurkand/department-system#12]
Master sertifikasi verdikten sonra return olmadıgı icin doctoral sertifikasi verme kontrolü yapıyor.
Ogretmenden ders removelayinca ogretmenin course listesinden o ders cıkıyor ama o dersin objesindeki ogretmen none olmuyor.

**Comment by mufurkand** [comment]
Master sertifikasını düzeltirim. Öğretmeni dersten kaldırmak için sekreterin appointLecturer() fonksiyonunu çağırman lazım, sadece kaldıramıyorsun öğretmeni yani; değiştirmen lazım.
