### ISSUE TITLE
Lecturers, Students ve Courses sistemde departman clasının içerisinden erişilmeli

### ISSUE THREAD

**Issue by imtryn** [mufurkand/department-system#3]

**Comment by imtryn** [comment]
courses içerisinde yaptığımız student list ekleme olayını department içine taşımamız gerekiyor saınırım?. hoca şöyle yazmış.
		"Each lesson in the department; course code, name, credit, course location, lecturer information, and ID information of the students taking the course."

**Comment by mufurkand** [comment]
Wat
