### ISSUE TITLE
Course'a öğrenci eklerken id information eklenmeli

### ISSUE THREAD

**Issue by imtryn** [mufurkand/department-system#5]
"While adding a course to the student, the student's ID information should be added to the relevant course."

**Comment by mufurkand** [comment]
Gereksiz çünkü zaten Student sınıfını geçiyoruz oraya

**Comment by imtryn** [comment]
Dolaylı yoldan student ID eklemiş oluyoruz aslında haklısın.

**Comment by imtryn** [comment]
Dolaylı yoldan Student ID eklemiş oluyoruz aslında haklısın.
